### Hanling imbalance dataset
1. Up Sammpling 
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibilicty
np.random.seed(123)

# Create a dataframe with two classes
n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

In [2]:
## CREATE MY DATAFRAME WITH IMBALANCE DATASET
class_0 = pd.DataFrame({
  'feature_1': np.random.normal(loc=0, scale=1,size=n_class_0),
  'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
  'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
  'feature_1':np.random.normal(loc=2, scale=1, size=n_class_1),
  'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
  'target': [1] * n_class_1
})

In [3]:
## Creating DataFrame
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [4]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [5]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [6]:
## Upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [7]:
from sklearn.utils import resample
df_minority_upsample = resample(df_minority,replace=True, ## sample with replacement
                                n_samples=len(df_majority),
                                random_state=42
)

In [11]:
df_minority_upsample.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [14]:
df_upsampled = pd.concat([df_majority,df_minority_upsample]).reset_index(drop=True)

In [18]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [19]:
# Set the random seed for reproducibilicty
np.random.seed(123)

# Create a dataframe with two classes
n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

## CREATE MY DATAFRAME WITH IMBALANCE DATASET
class_0 = pd.DataFrame({
  'feature_1': np.random.normal(loc=0, scale=1,size=n_class_0),
  'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
  'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
  'feature_1':np.random.normal(loc=2, scale=1, size=n_class_1),
  'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
  'target': [1] * n_class_1
})

## Creating DataFrame
df = pd.concat([class_0,class_1]).reset_index(drop=True)

## Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [20]:
## downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [21]:
from sklearn.utils import resample
df_majority_downsample = resample(df_majority,replace=False,
                                n_samples=len(df_minority),
                                random_state=42
)

In [22]:
df_majority_downsample.shape

(100, 3)

In [23]:
df_downsampled = pd.concat([df_minority,df_majority_downsample]).reset_index(drop=True)
df_downsampled

     feature_1  feature_2  target
0     1.699768   2.139033       1
1     1.367739   2.025577       1
2     1.795683   1.803557       1
3     2.213696   3.312255       1
4     3.033878   3.187417       1
..         ...        ...     ...
195  -0.168426   0.553775       0
196  -0.403366   0.081491       0
197  -0.269293   0.611238       0
198  -0.295829   0.671673       0
199  -0.553404   0.804438       0

[200 rows x 3 columns]