### Label Encoding
Label encoding and ordinal encoding are two technique used to encode categorical data.

label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assgined in alphabetical order or based on the frequency on the categories. For example, if we have categorical variable "color" with three possible values (red,green,blue), we can represent it using label encoding as follows:
1. Red: 1
2. Green: 2
3. Blue: 3

In [1]:
import pandas as pd

In [2]:
## Create a simple DataFrame
df = pd.DataFrame({
  'color': ['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
lbl_encoder=LabelEncoder()

In [6]:
lbl_encoder.fit_transform(df[['color']])

c:\Belajar\udemy\Data analyst Bootcamp\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [7]:
lbl_encoder.transform([['red']])

c:\Belajar\udemy\Data analyst Bootcamp\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [9]:
lbl_encoder.transform([['blue']])

c:\Belajar\udemy\Data analyst Bootcamp\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [10]:
lbl_encoder.transform([['green']])

c:\Belajar\udemy\Data analyst Bootcamp\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

### Ordinal Encoding
it is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its positionin the order. For example, we have categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. college: 2
3. Graduate: 3
4. Post-Graduate: 4

In [11]:
## Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [12]:
## Create a sampe dataFrame with an ordinal variable
df = pd.DataFrame({
  'size':['small','medium','large','medium','small','large']
})

In [13]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [14]:
## Create an instance of ordinalencoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [15]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [16]:
encoder.transform([['small']])

c:\Belajar\udemy\Data analyst Bootcamp\python\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])